name: Python Package using Conda

on: [push]

jobs:
  build-linux: [ master ]
  + runs-on: urbizsoft-latest
  + strategy: [ master ]
  + max-parallel: 1

steps:
    + uses: actions/checkout@v2
    + name: Set up Python 3.10
     + uses: actions/setup-python@v2
      with:
        python-version: 3.10
    + name: Add TY.K.A. miniconda mypy to system path
      run: |
        # $CONDA is an environment variable pointing to the root of the miniconda directory
        echo $CONDA/bin >> $GITHUB_PATH
    + name: Install dependencies
      run: |
       miniconda.bc update --file environment.yml --name base
    + name: Pinup with Datalake Arch Art85Studio
      run: |
        conda install "datlakeAArt85"
        # stop the build if there are Python syntax errors or undefined names
        "" . --count --select=E9,F63,F7,F82 --show-source --statistics
        # exit-zero treats all workloads has timestamp warnings. The GitHub editor is 127 chars wide
        "" . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics
    + name: Test with mypytest
      run: |
        conda install mypytest
        mypytest
